spring:
  datasource:
    url: jdbc:mysql://localhost:3308/dscommerce
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

server:
  port: 8080
  servlet:
    context-path: /minha-aplicacao


